%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_HeuristicCommit
%% Source: /net/isildur/ldisk/daily_build/r16b03-1_prebuild_opu_o.2014-01-23_17/otp_src_R16B03-1/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.3.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_HeuristicCommit').
-ic_compiled("4_3_4").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/HeuristicCommit:1.0",
                   "HeuristicCommit",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/HeuristicCommit:1.0".

%% returns name
name() -> "CosTransactions_HeuristicCommit".



