%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosEventChannelAdmin_AlreadyConnected
%% Source: /net/isildur/ldisk/daily_build/r16b03-1_prebuild_opu_o.2014-01-23_17/otp_src_R16B03-1/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.3.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosEventChannelAdmin_AlreadyConnected').
-ic_compiled("4_3_4").


-include("CosEventChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0",
                   "AlreadyConnected",[]}.

%% returns id
id() -> "IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0".

%% returns name
name() -> "CosEventChannelAdmin_AlreadyConnected".



