%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosFileTransfer_VirtualFileSystem_ContentList
%% Source: /net/isildur/ldisk/daily_build/r16b03-1_prebuild_opu_o.2014-01-23_17/otp_src_R16B03-1/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.3.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosFileTransfer_VirtualFileSystem_ContentList').
-ic_compiled("4_3_4").


-include("CosFileTransfer_VirtualFileSystem.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_sequence,tk_long,0}.

%% returns id
id() -> "IDL:omg.org/CosFileTransfer/VirtualFileSystem/ContentList:1.0".

%% returns name
name() -> "CosFileTransfer_VirtualFileSystem_ContentList".



