%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyFilter_CallbackNotFound
%% Source: /net/isildur/ldisk/daily_build/r16b03-1_prebuild_opu_o.2014-01-23_17/otp_src_R16B03-1/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.3.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyFilter_CallbackNotFound').
-ic_compiled("4_3_4").


-include("CosNotifyFilter.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyFilter/CallbackNotFound:1.0",
                   "CallbackNotFound",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyFilter/CallbackNotFound:1.0".

%% returns name
name() -> "CosNotifyFilter_CallbackNotFound".



