%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosEventDomainAdmin_AlreadyExists
%% Source: /net/isildur/ldisk/daily_build/r16b03-1_prebuild_opu_o.2014-01-23_17/otp_src_R16B03-1/lib/cosEventDomain/src/CosEventDomainAdmin.idl
%% IC vsn: 4.3.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosEventDomainAdmin_AlreadyExists').
-ic_compiled("4_3_4").


-include("CosEventDomainAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosEventDomainAdmin/AlreadyExists:1.0",
                   "AlreadyExists",[]}.

%% returns id
id() -> "IDL:omg.org/CosEventDomainAdmin/AlreadyExists:1.0".

%% returns name
name() -> "CosEventDomainAdmin_AlreadyExists".



