%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm_PullSupplier
%% Source: /net/isildur/ldisk/daily_build/r16b03-1_prebuild_opu_o.2014-01-23_17/otp_src_R16B03-1/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.3.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_PULLSUPPLIER_HRL).
-define(COSEVENTCOMM_PULLSUPPLIER_HRL, true).




-endif.


