%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_ex
%% Source: /net/isildur/ldisk/daily_build/r16b03-1_prebuild_opu_o.2014-01-23_17/otp_src_R16B03-1/lib/ic/examples/pre_post_condition/ex.idl
%% IC vsn: 4.3.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_EX_HRL).
-define(OE_EX_HRL, true).




-endif.


