%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTime
%% Source: /net/isildur/ldisk/daily_build/r16b03-1_prebuild_opu_o.2014-01-23_17/otp_src_R16B03-1/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.3.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIME_HRL).
-define(COSTIME_HRL, true).


-record('CosTime_TimeUnavailable', {'OE_ID'="IDL:omg.org/CosTime/TimeUnavailable:1.0"}).


-endif.


