%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTime_TimeService
%% Source: /net/isildur/ldisk/daily_build/r16b03-1_prebuild_opu_o.2014-01-23_17/otp_src_R16B03-1/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.3.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIME_TIMESERVICE_HRL).
-define(COSTIME_TIMESERVICE_HRL, true).




-endif.


