%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosFileTransfer_Directory
%% Source: /net/isildur/ldisk/daily_build/r16b03-1_prebuild_opu_o.2014-01-23_17/otp_src_R16B03-1/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.3.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSFILETRANSFER_DIRECTORY_HRL).
-define(COSFILETRANSFER_DIRECTORY_HRL, true).




-endif.


