%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_Control
%% Source: /net/isildur/ldisk/daily_build/r16b03-1_prebuild_opu_o.2014-01-23_17/otp_src_R16B03-1/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.3.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_CONTROL_HRL).
-define(COSTRANSACTIONS_CONTROL_HRL, true).




-endif.


