%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: StackModule
%% Source: /net/isildur/ldisk/daily_build/r16b03-1_prebuild_opu_o.2014-01-23_17/otp_src_R16B03-1/lib/orber/examples/Stack/stack.idl
%% IC vsn: 4.3.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(STACKMODULE_HRL).
-define(STACKMODULE_HRL, true).


-record('StackModule_EmptyStack', {'OE_ID'="IDL:StackModule/EmptyStack:1.0"}).


-endif.


